name: Build & Test
on: [ push ]
jobs:
  todo-application:
    runs-on: ubuntu-latest
    env:
      working-directory: ./todo-application-js
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: ${{env.working-directory}}
      - run: npm run test
        working-directory: ${{env.working-directory}}
